### ISSUE TITLE
code 65

### ISSUE THREAD

**Issue by rwrw01** [ruddj/sdm630-report#1]
have a sdm630 and installed your code and made the scripts executable. It's running but I get a code 65. How can I troubleshoot ?

ralph

**Comment by ruddj** [comment]
Hi Ralph,
 Code 65 means it failed to run modbus_read_input_registers(sdm630, 0000, 76, catcher).
On line 24 of code change from FALSE to "modbus_set_debug(sdm630, TRUE);" and see if it gives you any more details.

**Comment by rwrw01** [comment]
connection timed out.

I installed the ch341 driver for the board but ttyUSB0 doens't give me any output, I'll look in to that first.

edit, the board is mounted:
[   21.001560] usbserial: USB Serial support registered for ch341-uart
[   21.001677] ch341 1-1.3:1.0: ch341-uart converter detected
[   21.032646] usb 1-1.3: ch341-uart converter now attached to ttyUSB0

will check cable tommorow because the meter is already in use (main houseswitch) and I wil swicth the power off ..

**Comment by rwrw01** [comment]
bad wireconnection :nOOb:
