### ISSUE TITLE
upload error " MissingSectionHeaderError"

### ISSUE THREAD

**Issue by rwrw01** [ruddj/sdm630-report#2]
after succesful reading the SDM an other error when running the uploadscript occurs:

`Opening file: /var/tmp/ACT-2017-08-18-18-35.sdm
Traceback (most recent call last):
  File "pvoutput.py", line 117, in <module>
    sdmdata.read(dataFilePath)
  File "/usr/lib/python3.4/configparser.py", line 672, in read
    self._read(fp, filename)
  File "/usr/lib/python3.4/configparser.py", line 1058, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/var/tmp/ACT-2017-08-18-18-35.sdm', line: 1
'Opening /dev/ttyUSB0 at 9600 bauds (N, 8, 1)\n'
`

the SDM file:
`Opening /dev/ttyUSB0 at 9600 bauds (N, 8, 1)
Opening /dev/ttyUSB0 at 9600 bauds (N, 8, 1)
[MODBUS]
[01][04][00][00][00][4C][F1][FF]
Waiting for a confirmation...
<01><04><98><43><61><BB><C3><43><60><EC><2B><43><62><50><B4><3F><B9><C8><6E><3F><B7><A0><EA><3E><D7><32><32><43><83><15><2E><43><9E><21><43><00><00><00><00><43><A3><D1><6C><43><A1><56><34><42><BE><3E><27><C3><44><81><94><42><80><07><73><C2><BE><35><D6><3F><4C><D7><E3><3F><7A><E9><C6><3C><97><2E><A7><C2><13><6D><02><41><37><11><A8><C2><B1><E5><F2><43><61><A8><37><00><00><00><00><3F><91><6B><86><40><5A><21><49><00><00><00><00><44><10><9B><39><00><00><00><00><44><3A><5B><95><00><00><00><00><C3><63><98><C5><3F><6E><52><0D><00><00><00><00><C1><AB><5B><D5><00><00><00><00><42><48><10><5A><42><CE><72><B0><43><57><08><31><B7><70>
L1_Volt: 225.733444
L2_Volt: 224.922531
L3_Volt: 226.315247
L1_Amps: 1.451429
L2_Amps: 1.434598
L3_Amps: 0.420305
L1_Watt: 262.165466
L2_Watt: 316.259857
L3_Watt: 0.000000
L1_VAac: 327.636108
L2_VAac: 322.673462
L3_VAac: 95.121391
L1_PF: 0.800169
L2_PF: 0.980130
L3_PF: 0.018455
Avg_Volt: 225.657089
TOT_Amp: 3.408282
P_TOT_W: 578.425354
P_FACTO: 0.930939
Freq: 50.015968
IMPO_WH: 103.223999
EXPO_WH: 215.031998
READ: SUCCESSFUL
`

**Comment by ruddj** [comment]
Hi Ralph,
 Did you leave the debug statement from previous issue #1 set to TRUE? Please set it back to FALSE and it should hide the debug output.
Cheers.

**Comment by rwrw01** [comment]
I needed to recompile sdm630-usb.c of course

now to fix the 400 bad request code from pvoutput (feel like we're getting there).
